### PR TITLE
Add -e for exact searches (no fuzzy matches).

### PR DESCRIPTION
**Pull request by ecraven**
Only exact matches (or synonyms) are returned for simple searches.

### CODE REVIEW

**Comment by Dushistov** [comment]
@ecraven 

Command lines arguments and output to user are hard.
It need also update:

1. `doc/sdcv.1`

2. Update of all *.po and *.pot files in `po/` subdirectory, I don't mean translation,
   I mean add new lines for translation with help of `xgettext` and `msgmerge`

**Comment by ecraven** [comment]
OK, I added the new options to `doc/sdcv.1` and fixed a few typos.
I also regenerated the .po files, seems to have worked ok ;) There were a few other translations missing too.

**Comment by Dushistov** [comment]
@ecraven 

Great, thanks.

**Comment by ecraven** [comment]
Thank you for merging them all!

**Pull request merged**
